nelmio_cors:
    defaults:
        allow_origin: ['http://127.0.0.1:3000']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:3000']
