nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://172.20.10.10:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            expose_headers: ['Content-Disposition']
            max_age: 3600
