security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Changez "email" si vous utilisez un autre champ comme "username"

    firewalls:
        # Firewall pour la connexion via JWT
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour les routes protégées nécessitant un JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        # Exception : La route de connexion est publique
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }

        # Accès restreint aux utilisateurs authentifiés pour toutes les autres routes de l'API
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
