security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email 

    firewalls:
        # Firewall pour la connexion via JWT
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email 
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour les routes protégées nécessitant un JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
    # Route publique : accessible à tous
    - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
    - { path: ^/api/product, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }

    # Routes accessibles uniquement aux administrateurs
    - { path: ^/api/admin, roles: ROLE_ADMIN }

    # Routes accessibles uniquement aux utilisateurs connectés
    - { path: ^/api/user, roles: ROLE_USER }

    # Routes accessibles uniquement aux utilisateurs connectés (général)
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    