version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:80" # Exposer le serveur Symfony sur le port 8000
    volumes:
      - .:/var/www/html:rw,cached # Monter le code local pour le développement
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql:// ${MYSQL_USER}: ${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
    depends_on:
      - database

  database:
    image: mysql:8.3.0
    container_name: symfony_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8585:3306" # Port local : Port interne MySQL
    volumes:
      - database_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database_data: