services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # Vous devriez changer ce mot de passe en production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
    ports:
      - "8585" # Port local : Port interne MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql:rw
      # Vous pouvez utiliser un dossier monté en bind à la place pour faciliter le développement.
      # - ./docker/db/data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
