# config/routes.yaml
api_login_check:
    path: /api/login_check
    methods: [POST]

# Import des autres routes définies avec des attributs dans les contrôleurs
controllers:
    resource: ../src/Controller/
    type: attribute
