# config/routes.yaml
api_login_check:
    path: /api/login_check
    methods: [POST]

# Import des autres routes définies avec des attributs dans les contrôleurs
controllers:
    resource: ../src/Controller/
    type: attribute

app_add_product_image:
    path: /api/add-product/{id}/image_url
    methods: POST
    controller: App\Controller\UploadImageController::addImageUrl


